
export const products = [
  {
    id: 1,
    game: "Grow a Garden 2",
    title: "Dragon Seed",
    price: 79000,
    oldPrice: 120000,
    image: "/game/grow-a-garden.jpg",
    tag: "HOT",
    category: "seed",
    stock: 15,
  },
  {
    id: 2,
    game: "Grow a Garden 2",
    title: "Golden Pet",
    price: 129000,
    oldPrice: 159000,
    image: "/game/grow-a-garden.jpg",
    tag: "SALE",
    category: "pet",
    stock: 7,
  },
  {
    id: 3,
    game: "Steal a Brainrot",
    title: "Brain Jar",
    price: 55000,
    oldPrice: 90000,
    image: "/game/steal-brainrot.jpg",
    tag: "NEW",
    category: "item",
    stock: 31,
  },
  {
    id: 4,
    game: "Steal a Brainrot",
    title: "OP Bundle",
    price: 199000,
    oldPrice: 249000,
    image: "/game/steal-brainrot.jpg",
    tag: "HOT",
    category: "bundle",
    stock: 3,
  },
];